# Generated by Django 3.1.6 on 2021-02-10 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_description'),
        ('users', '0003_auto_20210208_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Доп. инф.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='products.product', verbose_name='Товар')),
                ('product_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='products.productprice', verbose_name='Цена товара')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'db_table': 'users_cart_items',
            },
        ),
    ]
